#!/bin/bash

split_string() {
    local string="$1"
    local delimiter="${2:- }"
    local words=()

    IFS="$delimiter" read -r -a words <<< "$string"

    echo "${words[@]}"
}

input_string="Hello world! This is a test."
result=$(split_string "$input_string")
echo "Array of words:"
echo "$result"
